lib/exchange_web/router.ex
defmodule ExchangeWeb.Router do
  use ExchangeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExchangeWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/registrations", RegistrationController, only: [:new, :create]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    get "/dashboard", DashboardController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExchangeWeb do
  #   pipe_through :api
  # end
end

lib/exchange/application.ex
defmodule Exchange.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Exchange.Repo, []),
      # Start the endpoint when the application starts
      supervisor(ExchangeWeb.Endpoint, []),
      # Start your own worker by calling: Exchange.Worker.start_link(arg1, arg2, arg3)
      # worker(Exchange.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Exchange.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ExchangeWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/exchange/moneda.ex
defmodule Exchange.Moneda do
  use Ecto.Schema
  import Ecto.Changeset
  alias Exchange.Moneda


  schema "monedas" do
    field :codigo, :string
    field :moneda, :string
    field :tasa_cambio, :decimal
    field :principal, :boolean

    timestamps()
  end

  @doc false
  def changeset(%Moneda{} = moneda, attrs) do
    moneda
    |> cast(attrs, [:moneda, :codigo, :tasa_cambio])
    |> validate_required([:moneda, :codigo, :tasa_cambio])
  end
end

lib/exchange/repo.ex
defmodule Exchange.Repo do
  use Ecto.Repo, otp_app: :exchange

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/exchange/usuario.ex
defmodule Exchange.Usuario do
  use Ecto.Schema
  import Ecto.Changeset
  alias Exchange.Usuario


  schema "usuarios" do
    field :nombre, :string
    field :email, :string
    field :crypto_password, :string
    field :password, :string, virtual: true

    timestamps()
  end

  def changeset(%Usuario{} = usuario, attrs) do
    usuario
    |> cast(attrs, [:nombre, :email, :password])
    |> validate_required([:email, :password])
    |> validate_length(:password, min: 5)
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
  end
end

lib/exchange_web/controllers/dashboard_controller.ex
defmodule ExchangeWeb.DashboardController do
  use ExchangeWeb, :controller
  plug ExchangeWeb.AuthenticatePlug when action in [:index]

  def index(conn, _params) do
    render conn, "index.html"
  end  
end

lib/exchange_web/controllers/page_controller.ex
defmodule ExchangeWeb.PageController do
  use ExchangeWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/exchange_web/controllers/session_controller.ex
defmodule ExchangeWeb.SessionController do
  use ExchangeWeb, :controller

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{"session"=> session_params}) do
    case ExchangeWeb.Session.login(session_params, Exchange.Repo) do
      {:ok, usuario} ->
        conn
        |> put_session(:current_user, usuario.id)
        |> put_flash(:info, "Logged in")
        |> redirect(to: "/")
      :error ->
        conn
        |> put_flash(:info, "Wrong email or password")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> delete_session(:current_user)
    |> put_flash(:info, "Logged out")
    |> redirect(to: "/")
  end
end

lib/exchange_web/views/dashboard_view.ex
defmodule ExchangeWeb.DashboardView do
  use ExchangeWeb, :view
end

lib/exchange_web/views/error_view.ex
defmodule ExchangeWeb.ErrorView do
  use ExchangeWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/exchange_web/views/layout_view.ex
defmodule ExchangeWeb.LayoutView do
  use ExchangeWeb, :view
end

lib/exchange_web/views/page_view.ex
defmodule ExchangeWeb.PageView do
  use ExchangeWeb, :view
end

lib/exchange_web/views/registration_view.ex
defmodule ExchangeWeb.RegistrationView do
    use ExchangeWeb, :view
end

lib/exchange_web/views/session_view.ex
defmodule ExchangeWeb.SessionView do
  use ExchangeWeb, :view
end

lib/exchange_web/templates/dashboard/index.html.eex
<h2>Hola, prro!</h2>
<h4>Solo puedes ver esto si estas logeado</h2>

lib/exchange_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Exchange!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if logged_in?(@conn) do %>
              <li><%= current_user(@conn).email %></li>
              <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
            <% else %>
              <li> <%= link "Register", to: registration_path(@conn, :new) %></li>
              <li> <%= link "Login", to: session_path(@conn, :new)%>
            <%end%>

          
            
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/exchange_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/exchange_web/templates/session/new.html.eex
<h2>Login</h2>
<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f ->%>
  <div class="form-group">
    <label for="Email">Email</label>
    <%= text_input f, :email, class: "form-control"%>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary"%>
  </div>
<%end%>